### ISSUE TITLE
'Recommended posts' sidebar widget is malfunctioning

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#281]
I just mentioned this in issue #280, but I just realized that it isn't only happening on posts below a single post on the infinite scroll. It's happening on any blog post. First of all, the 'recommended posts' widget takes about *30 seconds* to load for me. Second, once it does load, it's being all buggy and showing duplicate posts. Look: 

![screen shot 2016-04-04 at 10 34 36 pm](https://cloud.githubusercontent.com/assets/9164601/14269816/4037da9c-fab6-11e5-9cc8-e62a922f9223.png)

I'm in Chrome on my Mac.

**Comment by lostboyevsky** [comment]
Upon further testing, I've noticed that the problem is *definitely worse* on longer posts --- posts in which there are in-post ads. So in order to take a look at this problem, @dpatil-gmcs, check out some longer posts like this one: http://highexistence.com/12-psychological-tactics-donald-trump-uses-to-manipulate-the-masses/

**Comment by dpatil-gmcs** [comment]
@MSchirp  @lostboyevsky  I can see that the issue occurs only if page is scrolled up and down before the Sajari recommendations are loaded.
If the page is not scrolled till it is completely loaded the sidebar looks good.
I will have investigate the code and find the reason behind it.
Will Update you once I have a clue.

**Comment by MSchirp** [comment]
@dpatil-gmcs Why are they loading so slowly in the first place?

@mish15

**Comment by mish15** [comment]
@MSchirp looking at that page, they aren't being requested for about 20 seconds because there's so much other stuff loading (325 assets). They're put in the window load event, which is delayed quite a bit. @dpatil-gmcs might be better in the document.ready event? 4 sec vs 20 sec. 

![screen shot 2016-04-14 at 8 16 59 am](https://cloud.githubusercontent.com/assets/869412/14511249/7b46a50e-0219-11e6-8792-15cb3afa6561.png)

@lostboyevsky not sure about the duplicates. We aren't controlling the numbering, etc. Looking at the code, seems there might be a fall back to replace recommendations with a different type? I can't replicate this though.

**Comment by mish15** [comment]
@dpatil-gmcs might be easier to just use the HTML integration. Sample below, CSS is pretty close to your existing, but easy to change as needed. The HTML has the advantage that it loads optimistically, handles click tracking, rendering, etc for you.

```html
</style>
  <div data-sj-related data-sj-thumbnail data-sj-maxresults="4" data-sj-filters="post-type,post|!=series-id,0" data-sj-meta-category="Random + Awesome"></div>
  <div data-sj-recent data-sj-thumbnail data-sj-maxresults="3" data-sj-scales="post-id,1000000,1000000,5,0" filters="post-type,post" data-sj-meta-category="Random + Awesome"></div>
  <div data-sj-popular data-sj-thumbnail data-sj-maxresults="3" filters="post-type,post"></div>
</div>
```

```css
.sj-result-item {
  display: block;
  border-bottom: 1px solid #F3F5F6;
  padding: 0 0 20px;
  margin-bottom: 20px;
}
.sj-result-thumb {
  height: 100px;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  background-color: #283235;
  background-position: center center;
  background-repeat: none;
  position: relative;  
}
.sj-result-title {
  padding: 10px 0 0;
}
.sj-result-link {
  font-size: 14px;
  line-height: 140%;
  font-weight: bold;
  color: #283235;
  text-transform: uppercase;
}
.sj-result-meta-desc {
  display:none;
}
```
